#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ANDROID="$ROOT/android"
SRC="$ANDROID/app/src/main/java/global/gibp/mail"

if [[ ! -d "$ANDROID/app" ]]; then
  echo "android/ does not exist. Run: npx cap add android" >&2
  exit 1
fi

mkdir -p "$SRC"
cp "$ROOT"/native/android/java/*.java "$SRC"/

GRADLE="$ANDROID/app/build.gradle"
if [[ ! -f "$GRADLE" ]]; then
  echo "Expected $GRADLE" >&2
  exit 1
fi
if ! grep -q 'androidx.work:work-runtime:2.12.0' "$GRADLE"; then
  sed -i '/^dependencies[[:space:]]*{/a\    implementation "androidx.work:work-runtime:2.12.0"' "$GRADLE"
fi

MANIFEST="$ANDROID/app/src/main/AndroidManifest.xml"
sed -i 's/android:allowBackup="true"/android:allowBackup="false"/' "$MANIFEST"
if ! grep -q 'android.permission.POST_NOTIFICATIONS' "$MANIFEST"; then
  sed -i '/<manifest/a\    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />' "$MANIFEST"
fi

# Resend OAuth returns to the installed app through a private-use URI scheme.
# Keep this overlay idempotent because android/ is regenerated by Capacitor in CI.
if ! grep -q 'android:scheme="global.gibp.mail"' "$MANIFEST"; then
  python3 - "$MANIFEST" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text()
anchor = "        </activity>"
if anchor not in text:
    raise SystemExit("Unable to find MainActivity closing tag in AndroidManifest.xml")

intent = """            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:scheme="global.gibp.mail"
                    android:host="oauth"
                    android:path="/resend" />
            </intent-filter>
"""
text = text.replace(anchor, intent + anchor, 1)
path.write_text(text)
PY
fi

echo "Applied GIBP Mail Android native background/OAuth overlay."
